name: sketchmind
description: Hayal Et - AI YapsÄ±n | Ã‡ocuklar iÃ§in hikaye, gÃ¶rsel ve ses Ã¼retimi uygulamasÄ±.
publish_to: 'none' # Yerel geliÅŸtirme iÃ§in
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #internet baÄŸlantÄ±sÄ±
  connectivity_plus: ^6.0.2

  # ðŸ§© Firebase Paketleri
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.3.0
  firebase_storage: ^12.1.0

  # âš™ï¸ Uygulama Paketleri
  provider: ^6.1.2
  go_router: ^14.0.1
  http: ^1.2.2
  flutter_tts: ^4.0.2
  lottie: ^3.1.0
  path_provider: ^2.1.3
  audioplayers: ^5.0.0

  # ðŸŽ¨ UI / GÃ¶rseller
  google_fonts: ^6.2.1
  animations: ^2.0.8
  dart_openai: ^5.1.0
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/stories/
    - assets/images/
    - assets/lottie/
    - .env
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700
